### ISSUE TITLE
Some `maybe` questions

### ISSUE THREAD

**Issue by Magnogen** [TodePond/DreamBerd#1]
```js
if (maybe) print("maybe is true")!
if (;maybe) print("maybe is false")!
```
Some possible options:
- `if (maybe)` can run randomly, so `maybe` and `;maybe` can mean the same thing
  - what would happen with variables?
    ```js
    const const thingy = maybe!
    if (thingy) print("first is true")!
    if (thingy) print("maybe s are evaluated when assigned, rather than when called")!
    ```
    In this case, `thingy == thingy` will always be `true`, but `thingy == true` could be `true` or `false`, and `thingy == false` could be `false` or `true`. 
  - How would `maybe` be differentiated from `true` and `false`? 
- `if (maybe)` and `if (;maybe)` can never run, almost like a trinary thing? Then something like `maybe == maybe` would be `true`?
  - This would help with differentiating, but it would need something else for this kind of thing. Perhaps something like
    ```js
    if (thingy == maybe) {
        // executes if it's maybe
    } else {
        // executes if it's a traditional boolean
    }
    ```
    Or something similar? Maybe even
    ```js
    if ( ... ) {
        // executes when true
    } else {
        // executes when false
    } perhaps {
        // executes when maybe
    }!
    ```
I'd love to hear your thoughts

**Comment by TodePond** [comment]
I think the `perhaps` keyword is great!! Let's do it

**Comment by TodePond** [comment]
Maybe `true = maybe` could be true (on the loosest comparison precision)

**Comment by Magnogen** [comment]
One... and a half... bits...

I'm liking this language already! 😂

**Comment by TodePond** [comment]
I put it in the spec
