### ISSUE TITLE
Idea: remove code completely, use comments to tell the user what to do instead

### ISSUE THREAD

**Issue by labbo-lab** [TodePond/DreamBerd#10]

**Comment by TodePond** [comment]
I like it

**Comment by Magnogen** [comment]
```js
// todo: figure out how to word how this program works well so that people know exactly how to do it and what you're talking about but not too much like it is now and all in one sentence because that's weird and I just want to make some cool code because code is cool
```

**Comment by labbo-lab** [comment]
it kinda reminds me of a probably dumb idea I had: direct ideas to code, almost like what copilot does with comments

Basically there's machine code, and then there's "Human Code"

**Comment by Magnogen** [comment]
That's sounds a bit like a story-lang idea I had a little while back, I can't remember the exact syntax, but it was something like:

```
Once upon a time, there lived a boy named Luke. Luke was brilliant, and he had lots of friends - one of them was Max, another was Linn, and there was also Steve.

Max's favourite number is 18, and Linn's is twenty-four. Together, they like Steve's favourite number

One day, Steve shouted his favourite number. Then Luke shouted a new line character!

The end.
```

Yes that prints the result of `18 + 24`. 😁

**Comment by labbo-lab** [comment]
hmmm, some syntax for this: 

`Print: //Type [string] yourself
Any math: //Ok, grab a calculator and type in [math]
Functions without parameters: //Ok, remember this: Whenever I ask you to [function name], I want you to [describe code]
Functions with parameters: //Ok, remember this: Whenever I ask you to [function name], I want you to [describe code]. Oh yeah, I also need to know [parameters]`

this could be phrased however you want

**Comment by Magnogen** [comment]
`DreamBerd`? More like `NightmareBerd`

**Comment by TodePond** [comment]
This is now possible by using ChatGPT!
