### ISSUE TITLE
Make Berd   S m o o t h 

### ISSUE THREAD

**Issue by labbo-lab** [TodePond/DreamBerd#110]
![path (8)](https://github.com/TodePond/DreamBerd/assets/62490883/25fab7cf-777f-40a8-84fd-827691eb5c75)

TODO:
- [x] Add Timbs(!!!!)
- [x] Optimize as much as possible

**Comment by TodePond** [comment]
nice! timbs would be great

**Comment by labbo-lab** [comment]
> nice! timbs would be great

![path (9)](https://github.com/TodePond/DreamBerd/assets/62490883/7bdc6f42-7cfa-43c4-89a1-ee449e0948dd)
Done
