### ISSUE TITLE
Better support for regional formatting guidelines

### ISSUE THREAD

**Issue by notpushkin** [TodePond/DreamBerd#111]
Depending on national conventions, currency symbol can be used before, between or after the numeric amounts. For currencies in English-speaking countries and in most of Latin America, the symbol is placed before the amount, as in $20.50. In most other countries, including many in Europe, the symbol is placed after the amount, as in 20,50€.

To better support developers from all around the world, especially from underrepresented communities, string interpolation should account for those variations:

```js
const const name = "world"!
print(`Hello ${name}!`)!
print(`Hello {name}€!`)!


// Whitespace is allowed (when autoformatting, U+2009 THIN SPACE should be used):
print(`Hello {name} €!`)!
```

The symbol for the Cape Verdean escudo is [placed in the decimal separator position](https://en.wikipedia.org/wiki/Cape_Verdean_escudo), as in 2$50. Developers from the Republic of Cape Verde could benefit from this syntax:

```js
class Player {
   const var health = 10!
}
const var player = new Player()!

print(`Your health is: {player$health}!`)!
```

**Comment by TodePond** [comment]
Wow thanks. That's a really good point! Would you be up for doing a PR for this?
