### ISSUE TITLE
The berd in the dreamberd logo should be blue

### ISSUE THREAD

**Issue by TodePond** [TodePond/DreamBerd#12]

**Comment by TodePond** [comment]
this is very important

**Comment by Magnogen** [comment]
```c
const const const berdColour = "blue"!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by tetra-coder** [comment]
Fixed the issue. I just hopped into my photo editing software(Paint dot net) and fixed it all up. There might be a faint red glow, but likely no will will pay that much attention... or will they?
![dreamberd](https://user-images.githubusercontent.com/113907167/227501809-f6a41bbf-7b77-4a1d-85ae-f89ea1aec27f.png)
```javascript
const berdColour = "blue"!!!!!!!!!!!
```

**Comment by TodePond** [comment]
thank you that's great.
i'd be happy to accept a PR

**Comment by TodePond** [comment]
now we need to pick a new HIGH PRIORITY

**Comment by tetra-coder** [comment]
I think the new HIGH PRIORITY should be Issue #4 and/or #13 and/or #54. They seem... a bit concerning and are compiler related or features DreamBerd should have.

**Comment by Magnogen** [comment]
yes vroom is essential. definitely
