### ISSUE TITLE
Add support for the Greek question mark

### ISSUE THREAD

**Issue by 96-LB** [TodePond/DreamBerd#135]
I identify as ancient Greek, so I would like to be able to express my uncertainty about lines of code using `;`, the ερωτηματικό. For example:

```js
print("Hello world")?
print("Hello world"); //equivalent to above
print("Hello world"); //this one is bad, obviously
```

I believe this change would simultaneously increase the diversity and cultural awareness of DreamBerd and reduce confusion about how to express confusion for ancient Grecians such as myself.

**Comment by TodePond** [comment]
feels like punching down
