### ISSUE TITLE
Built-in Support for Tailwind CSS

### ISSUE THREAD

**Issue by SonMooSans** [TodePond/DreamBerd#162]
As we know, we can have `.DBX` files, it's also known that creating a `.css` file wastes a lot of time.
It would be great to have tailwind css without any other tools.

```db
funct App() => {
   return <div tw="bg-red-300">Hello world!</div>
}
```

**Comment by Gary50613** [comment]
Should have build in router like nextjs and other frameworks

**Comment by klarkc** [comment]
But actually it would not add or translate to anything in runtime, giving flexibility on how to define HTML classes according to the DBX syntax
