### ISSUE TITLE
There should be more issues

### ISSUE THREAD

**Issue by TodePond** [TodePond/DreamBerd#2]
At least 9 I think

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9

**Comment by TodePond** [comment]
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10

**Comment by Magnogen** [comment]
- [x] 4!

**Comment by TodePond** [comment]
On second thoughts, let's be realistic and aim for 9 instead

**Comment by TodePond** [comment]
a couple new issues: #8 #7

**Comment by Magnogen** [comment]
Cheep cheep! #9

**Comment by TodePond** [comment]
Almost there #10

**Comment by TodePond** [comment]
I should specify, there should be at least 9 open issues!

**Comment by TodePond** [comment]
Oh dear there's now 8 issues
Re-opening

**Comment by TodePond** [comment]
Great! There's 9 again!
Closing

**Comment by TodePond** [comment]
There seems to be an issue. I'll leave it open for now

**Comment by Magnogen** [comment]
I knew this would happen, I was going to write an issue to suggest the issue with this issue. I should have done it sooner

**Comment by Ringlings** [comment]
Sorry to revive an old issue, but `wontfix` when the issue is closed as fixed? This makes no sense at all!

**Comment by labbo-lab** [comment]
How about maybefix

**Comment by TodePond** [comment]
Uh oh

**Comment by TodePond** [comment]
fixed (maybe)
