### ISSUE TITLE
Let RegExp match /Reg(ular)?[eE]x(press(ion)?|p)?/

### ISSUE THREAD

**Issue by rinodrummer** [TodePond/DreamBerd#220]
For 3 reasons:
    - No one likes to be under pressure and "pression" in some languages is similar to "pressure";
    - Everyone dreams to travel on the Regular Express!
    - [I like trains](https://www.youtube.com/watch?v=5DjOL2we8ko).

**Comment by TodePond** [comment]
wanna submit a PR? :)

**Comment by rinodrummer** [comment]
> wanna submit a PR? :)

Absolutely, I'm gonna try doing it!

**Comment by rinodrummer** [comment]
> Just a random idea, can I "express" myself?

I'm on the hype **train**, waiting to know you opinion!

**Comment by rinodrummer** [comment]
Improvements: Updated `/Reg(ular)?[eE]x(pression|press|p)?/` in `/Reg(ular)?[eE]x(press(ion)?|p)?/` to make it more comprehensible.
