### ISSUE TITLE
Make the spec more self-contained i.e. explain unexplained language constructs and builtins

### ISSUE THREAD

**Issue by FeldrinH** [TodePond/DreamBerd#229]
The examples currently contain a number of things that are not mentioned in the specification at all. They should probably be at least mentioned somewhere.

Examples of mysterious constructs in the examples include:
* `addEventListener` and `requestAnimationFrame` functions
* some kind of maps/dictionaries seen in the booleans example (`{}` literal)
* the `await` keyword seen in front of `next` in examples
* the `after` keyword seen in the `next` example

**Comment by TodePond** [comment]
it's ECMAScript unless otherwise stated

(except for `after` - that's from a joke that was removed, that one could go)

**Comment by FeldrinH** [comment]
For a perfect programming language to defer to something as imperfect as ECMAScript seems somewhat blasphemous.

**Comment by FeldrinH** [comment]
On a more practical note: defering to ECMAScript makes it practically impossible to build a self-contained interpreter (i.e. one that doesn't contain an ECMAScript runtime), which is a pity, cause I really wanted to do that.

**Comment by FeldrinH** [comment]
Also, a nitpick: `addEventListener` and `requestAnimationFrame` are not part of ECMAScript and are in fact absent in NodeJS, Deno and a number of other ECMAScript-compliant runtimes.

**Comment by TodePond** [comment]
Sorry to interrupt - I just - actually - I -

I -

**Comment by FeldrinH** [comment]
Superseded by https://github.com/TodePond/DreamBerd/issues/234.
