### ISSUE TITLE
const is not Constant enough

### ISSUE THREAD

**Issue by DanProudfoot** [TodePond/DreamBerd#24]
If I define a `const const`, I want it constant dammit!

I think constants should remain set for the lifetime of the computer.

**Comment by TodePond** [comment]
Maybe we should add `const const const`

**Comment by DanProudfoot** [comment]
Maybe `permanent`?

**Comment by DanProudfoot** [comment]
And then I guess you'd want a `ephemeral`, which would create a variable you need want for very long

**Comment by Magnogen** [comment]
It throws an error if it doesn't get used on the very next line of code

**Comment by wisniewski94** [comment]
How about a temporary? The variable that lives only during assignment.

```
temp myVar = true
print(myVar) // Error: myVar is undefined
```

**Comment by TodePond** [comment]
I think this calls for a concept of 'lifetimes' inspired by Rust.

We could support a few different units of measurement for lifetimes:
```c
const const foo<1s> = "foo"! //lasts for one second
const const bar<1> = "bar"! //lasts for one line
```

The default lifetime could be until the end of the program.
But you could make the lifetime longer if you want you want an even constant-er constant!
const const baz<Infinity> = "baz"!

**Comment by Magnogen** [comment]
Oooo I love the idea of lifelines!

**Comment by TodePond** [comment]
Implemented in https://github.com/TodePond/DreamBerd/releases/tag/v0.9.9.9.9.9.9.9.9
