### ISSUE TITLE
get to the top of hackernews

### ISSUE THREAD

**Issue by TodePond** [TodePond/DreamBerd#32]

**Comment by TodePond** [comment]
4 points is my personal record for a hackernews post: https://news.ycombinator.com/item?id=33824986

**Comment by TodePond** [comment]
it's at 6 points now!

**Comment by TodePond** [comment]
nice 7 i think we're almost there

**Comment by TodePond** [comment]
lets go https://news.ycombinator.com/item?id=36178437

**Comment by TodePond** [comment]
we got a big one: 

https://news.ycombinator.com/item?id=36183683

**Comment by TodePond** [comment]
New record
![Screenshot_20230604-181518](https://github.com/TodePond/DreamBerd/assets/15892272/817a6afe-5dbb-4651-96fa-73c0dea6c721)

**Comment by TodePond** [comment]
We made it to the top! I didn't get a screenshot though

**Comment by eMBee** [comment]
the best i could find is http://web.archive.org/web/20230605030557/https://news.ycombinator.com/ at place 6

and here it is reaching 500 points: http://web.archive.org/web/20230605055709/https://news.ycombinator.com/

**Comment by treeplate** [comment]
This is still pinned
