### ISSUE TITLE
Make a website to intreduce the language better

### ISSUE THREAD

**Issue by Youssef535** [TodePond/DreamBerd#33]
In opinion-making a web page to introduce the language it's a good choice and it will be better if you use the language itself on it.

**Comment by TodePond** [comment]
good idea, I'll assign this one to you, good luck :)

**Comment by Youssef535** [comment]
i have work to do so it will take some time to do that maybe if a developer can join me that will be great

**Comment by TodePond** [comment]
It's ok I made one: https://beta.tldraw.com/r/dreamberd
