### ISSUE TITLE
Feature : Overriding a primitive value ?

### ISSUE THREAD

**Issue by OsaidAlhomedy** [TodePond/DreamBerd#36]
As a dynamic language, I wrote the following code :
```py
3=2!!!
print((1+1) ==== 3)!
```
But for some odd reason, it doesn't work as expected and prints false!
Please consider adding this feature as soon as possible

**Comment by TodePond** [comment]
good spot

**Comment by Magnogen** [comment]
Why don't you try:

```c
delete 2!
print((1+1) ==== 3)!
```
Does that work how you expect?

**Comment by TodePond** [comment]
just to follow up, would you like to make a PR for this?

**Comment by TodePond** [comment]
This has been done! Thanks for the idea: https://github.com/TodePond/DreamBerd/pull/48
