### ISSUE TITLE
accessible FYP

### ISSUE THREAD

**Issue by loglot** [TodePond/DreamBerd#363]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/88983354/b1b57f50-0cfb-444a-82ea-536ea827dcd4

**Comment by TodePond** [comment]
Sure, please could you record yourself reading out the page? 

no text to speech or AI voice allowed

**Comment by loglot** [comment]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/88983354/16cef0d9-cf18-413e-8c8e-c1b7fcfe4d33

**Comment by mybearworld** [comment]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/130385691/93d6043c-399e-4b15-bd8f-3c6bf65f53ff

https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/130385691/0c217812-4d45-4d65-af54-9ff1e8b17754

https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/130385691/92f0ec84-a3da-44e2-8c27-18e9906a1363

**Comment by mybearworld** [comment]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/130385691/5931b1a0-23ef-4910-a6ed-b6f3ea801259

**Comment by loglot** [comment]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/88983354/a9b555ed-1c1f-4851-a4e4-da2e673a400f

**Comment by mybearworld** [comment]
> real.voice.mov

https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/130385691/f22a4d84-0a00-4450-ae61-55971287bd50

**Comment by loglot** [comment]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/88983354/dd75893b-0581-4cf7-ac82-a6437560a0af

**Comment by loglot** [comment]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/88983354/467f844b-d50f-45c2-81c4-7d86a849c985

**Comment by mybearworld** [comment]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/130385691/9304a3f9-32d7-497c-ad09-694783f8894e

**Comment by loglot** [comment]
https://github.com/TodePond/WhenWillProgrammersStopMakingDecisionsForOurSocietyAndJustLeaveUsAloneAlsoHackerNewsIsAVileWebsite/assets/88983354/f99ffd28-2fb0-43b3-a282-275dfba4375f
