### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by treeplate** [TodePond/DreamBerd#390]
There is no documentation in the latest commit of this, C repo, or DreamBerd repo.

**Comment by TodePond** [comment]
Hey sorry this is the old repo

Please go to the new repo at https://github.com/TodePond/DreamBerd

**Comment by loglot** [comment]
> Hey sorry this is the old repo
> 
> Please go to the new repo at https://github.com/TodePond/DreamBerd

^^^

**Comment by treeplate** [comment]
Moved to https://github.com/TodePond/DreamBerd/issues/7 and https://github.com/TodePond/C/issues/3
