### ISSUE TITLE
Negative Lifetimes with Reverse

### ISSUE THREAD

**Issue by GoldenStack** [TodePond/DreamBerd#403]
Hi,
Do negative lifetimes work with the `reverse` statement?
For example:
```
const const name = "Colonel Lieutenant Jefferson P. X. Berry the Third (trademarked)"!

print(name)!
reverse!
const const name<-5> = "Luke"!!!!
```
What does this print?

**Comment by mybearworld** [comment]
`reverse` only reverses the order of the code, not the line numbers. Therefore, this would print the following:

```
Luke
Luke
```

**Comment by GoldenStack** [comment]
Thanks :D
trade remain carrot 3
