### ISSUE TITLE
Add Regex type

### ISSUE THREAD

**Issue by Pomierski** [TodePond/DreamBerd#41]
It could be used to create a type that allows assigining email address only

Consider following example:

```const const email: Regex<(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])> = "mymail@mail.com"!```

**Comment by TodePond** [comment]
great idea!

should we call it Regex, Regexp, RegEx, or RegExp?

**Comment by Pomierski** [comment]
Can't decide. Maybe all of them to avoid confusion?

**Comment by TodePond** [comment]
perhaps something like `/Reg[eE]x(p*)/`

**Comment by Pomierski** [comment]
Excellent idea

**Comment by Magnogen** [comment]
```c
const const email = /Reg[eE]x(p*)/<(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])>
```
I love this syntax, it makes a lot of sense and should definitely be implemented immediately.

**Comment by TodePond** [comment]
@Magnogen remember the exclamation mark at the end!

**Comment by Magnogen** [comment]
Aha! Yes! Thank you :)

**Comment by TodePond** [comment]
Would you like to do a PR for this @Pomierski?

**Comment by Pomierski** [comment]
I would love to. Done https://github.com/TodePond/DreamBerd/pull/46
