### ISSUE TITLE
Logo still depicts number "2"

### ISSUE THREAD

**Issue by Nekosis** [TodePond/DreamBerd#416]
DreamBerd 3 has released, but the logo displayed in the README still depicts the number 2:
![image](https://github.com/TodePond/DreamBerd/assets/37462865/cad5d5c2-62b8-4113-8633-a80f2071cb74)
This should be changed to avoid confusion against what the current version of the language is.

**Comment by kotlinc** [comment]
just add an extra line

**Comment by mybearworld** [comment]
@TodePond Could you close this now? I forgot to add the "Resolves #xyz" thing to the PR

**Comment by Nekosis** [comment]
I'll close it. Nice job @mybearworld :)
