### ISSUE TITLE
DreamBerd can cause harm or discomfort to individuals or groups.

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [TodePond/DreamBerd#53]
![image](https://user-images.githubusercontent.com/65097669/223885713-f54846fd-4697-4a5b-90ad-7d8499477935.png)

**Comment by tetra-coder** [comment]
That's not really an issue, you asked it too harshly and didn't even tell IT what was DreamBerd.
Check the compiling section in the `README.md` for a correct way to do it. It should fix it.
https://github.com/TodePond/DreamBerd/#compiling

**Comment by FoxNerdSaysMoo** [comment]
Apologies,
I did in fact provide it with the proper information to compile DreamBerd. That noted, I think you are right that I was likely too harsh to the compiler. It may be beneficial to have a "kindness" section or something similar in the README to ensure that future users can avoid causing harm or discomfort to individuals or groups.

**Comment by TodePond** [comment]
We're gonna have to unlaunch DreamBerd

**Comment by TodePond** [comment]
I have unlaunched DreamBerd in response to this https://github.com/TodePond/DreamBerd/releases/tag/v0.9.9.9.9.9.9.9.9
