### ISSUE TITLE
how do we not have this feature

### ISSUE THREAD

**Issue by mindplay-dk** [TodePond/DreamBerd#566]
C is winning damnit

![20240124_221808](https://github.com/TodePond/DreamBerd/assets/103348/cbb432f3-30c1-44e4-9edd-2b48a69a3e71)

https://twitter.com/nakedMCSE/status/1750033071095603409

**Comment by mybearworld** [comment]
```js
var const b = 0!
var const a = 0!
when (a) {
  a = ++b!
}
if (a == 1 && a == 2 && a == 3) {
  print("Yes, it does")!
}
```
