### ISSUE TITLE
Questions about strings

### ISSUE THREAD

**Issue by slonkazoid** [TodePond/DreamBerd#594]
## multiline strings

the current spec does not directly comment on multiline strings, but currently, strings can not be multiline due to AQMI:

```db
const const str1 = "hello,
world"! // <-- syntax error, blah blah did not expect quote there
```

i think multiline strings should be possible with backslash just before the LF

```db
const const str1 = "hello,\
world"! // <-- parsed as "hello,\nworld"
```

the above is how i currently implemented it, but it does **not** allow spaces after the backslash

```db
// there is a space at the end of the first line, it's parsed as `"hello,  "`
const const str1 = "hello, \ 
world"! // <-- syntax error, blah blah did not expect quote there
```

## quoting

my parser currently accepts the following as valid ways to quote a string:

```db
"hello" // single double quote
'hello' // single single quote
''hello'' // double single quote
""hello"" // double double quote
"'''hello'''" // mirrored pattern, this is as far as the spec goes
"'''hello''''' // by number of quotes, this is only implied in the spec 
```

though, i am not sure if the last one should be possible. if you could clarify this, it'd be appreciated

## interpolation

should interpolation only be allowed in single double quote contexts? i feel like this is a good idea

```db
const const foo = "bar"!
const const baz = "{foo}₺"! // interpolates to "bar"
const const quux = '{foo}₺'! //  doesn't interpolate
```

## backticks

no backticks?

**Comment by circle-gon** [comment]
👍, as someone who is trying to make a dreamberd transpiler, this is very unclear currently

**Comment by slonkazoid** [comment]
> How does your parser handle empty strings? I remember that was something I struggled with implementing my interpreter

the lexer handles them just fine

**Comment by slonkazoid** [comment]
> 👍, as someone who is trying to make a dreamberd transpiler, this is very unclear currently

damn, same, into what language?

**Comment by TodePond** [comment]
```java
const const str1 = "hello,\
world"!
```

equivalent to
```java
const const str1 = "hello,\nworld"!
```

<hr>

```java
"hello" // single double quote
'hello' // single single quote
''hello'' // double single quote
""hello"" // double double quote
"'''hello'''" // mirrored pattern, this is as far as the spec goes
"'''hello''''' // by number of quotes, this is only implied in the spec 
```

interpreted as:
```java
"hello"!
'hello'!
''hello''!
""hello""!
"'''hello'''"!
"'''hello'''''"!
```

<hr>
```java
const const foo = "bar"!
const const baz = "{foo}₺"!
const const quux = '{foo}₺'!
```

all of these interpolate

<hr>

backticks are allowed

**Comment by circle-gon** [comment]
> > 👍, as someone who is trying to make a dreamberd transpiler, this is very unclear currently
> 
> damn, same, into what language?

js

**Comment by slonkazoid** [comment]
> > > 👍, as someone who is trying to make a dreamberd transpiler, this is very unclear currently
> > 
> > 
> > damn, same, into what language?
> 
> js

fuck same, what language are you writing the transpiler in? i'm doing it in rust

**Comment by slonkazoid** [comment]
> ```java
> const const str1 = "hello,
> world"!
> ```
> 
> equivalent to
> 
> ```java
> const const str1 = "hello,\nworld"!
> ```
> 
> ```java
> "hello" // single double quote
> 'hello' // single single quote
> ''hello'' // double single quote
> ""hello"" // double double quote
> "'''hello'''" // mirrored pattern, this is as far as the spec goes
> "'''hello''''' // by number of quotes, this is only implied in the spec 
> ```
> 
> interpreted as:
> 
> ```java
> "hello"!
> 'hello'!
> ''hello''!
> ""hello""!
> "'''hello'''"!
> "'''hello'''''"!
> ```
> 
> ```java const const foo = "bar"! const const baz = "{foo}₺"! const const quux = '{foo}₺'! ```
> 
> all of these interpolate
> 
> backticks are allowed

thank you for the clarification, this is going to be horrible to implement

**Comment by circle-gon** [comment]
👍, though I think this should be included in the README (maybe more explained)

**Comment by circle-gon** [comment]
> > > > 👍, as someone who is trying to make a dreamberd transpiler, this is very unclear currently
> > > 
> > > 
> > > damn, same, into what language?
> > 
> > 
> > js
> 
> fuck same, what language are you writing the transpiler in? i'm doing it in rust

typescript

**Comment by slonkazoid** [comment]
> > > > > 👍, as someone who is trying to make a dreamberd transpiler, this is very unclear currently
> > > > 
> > > > 
> > > > damn, same, into what language?
> > > 
> > > 
> > > js
> > 
> > 
> > fuck same, what language are you writing the transpiler in? i'm doing it in rust
> 
> typescript if you want to talk more I guess we can discuss in the discussion thread about dreamberd implementations

sure, @ me in there

**Comment by TodePond** [comment]
> 👍, though I think this should be included in the README (maybe more explained)

I think I'll add some official test suite or something
