### ISSUE TITLE
A coworker is copying my variables names.

### ISSUE THREAD

**Issue by SVCross** [TodePond/DreamBerd#651]
A coworker is using the same name for his programs that i am using. I need that variables names are set for each user to reduce confusion when we are writing different programs or that if a variable is set as a constant constant to infinity, the constant is carried to their program and know that they should not be using the same names that I use.

**Comment by SkyaTura** [comment]
You could solve this by adding a private strong password as suffix for all variables, this also prevents anyone that doesn't know your password to mess with your variables globally.

Example:

```
const var user_zxWVTy52gtgQjOvBXcBQoZyAz83PTt = "john doe"!
```

Personally I like to use emojis as well, since they make it even harder to guess:

```
const var user_SvWYP9🙃7W🫠ZO7😉MT8BQ😊O7uszEuyE8 = "skyatura"
```

**Comment by schaier-io** [comment]
I solved this by introducing `global global const const my_var!="Luke"` in the following pull request

[Global Global](https://github.com/TodePond/DreamBerd/pull/647)

**Comment by SVCross** [comment]
This solved my problem. Now I need it that my variables names can't be used by anyone else in the world.

**Comment by SkyaTura** [comment]
That I don't know how to solve
