### ISSUE TITLE
Not enough stars

### ISSUE THREAD

**Issue by TodePond** [TodePond/DreamBerd#7]
There aren't enough stars on this repo. Please give a star to help out!

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [x] 9

**Comment by TodePond** [comment]
Only one more needed!

**Comment by abhinav-singh-github** [comment]
I did it! This repo has now got 10 stars!

**Comment by TodePond** [comment]
Great news!

**Comment by Magnogen** [comment]
Is 195 enough? It has a 9 in it...

**Comment by TodePond** [comment]
Yes that's enough but maybe now we should get some more

**Comment by tetra-coder** [comment]
![wat](https://user-images.githubusercontent.com/113907167/206917147-08a3075f-3775-4bae-b1bd-921bbbab83d9.png)
the number of stars is exploding like madness

**Comment by Magnogen** [comment]
I know right?! There should be another video saying that, with enough patience and effort, you can create anything. Even despite critics on the internet.
